language: objective-c
xcode_project: JenkinsiOS.xcodeproj
xcode_scheme: JenkinsiOSTests
osx_image: xcode8.2
xcode_sdk: iphonesimulator10.0

script:
- xcodebuild clean build test -project JenkinsiOS.xcodeproj -scheme JenkinsiOSTests  -destination "platform=iOS Simulator,name=iPhone 7,id=E40727B3-41FB-4D6E-B4CB-BFA87109EB12" -json
