language: objective-c
xcode_project: JenkinsiOS.xcodeproj
xcode_scheme: JenkinsiOSTests
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.0

script:
- xcodebuild clean build test -project JenkinsiOS.xcodeproj -scheme JenkinsiOSTests  -destination "platform=iOS Simulator,id=85AF1F51-F2EB-4A4D-930B-0E5761511A45" -json
