language: objective-c
xcode_project: JenkinsiOS.xcodeproj
xcode_scheme: JenkinsiOSTests
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.0

script:
- xcodebuild clean build test -project JenkinsiOS.xcodeproj -scheme JenkinsiOSTests  -destination "platform=iOS Simulator,id=34FA4749-C467-4D45-9F8E-E31AEDDC39C2" -json
