language: objective-c
xcode_project: JenkinsiOS.xcodeproj
xcode_scheme: JenkinsiOSTests
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.0

cache:
- bundler

before_install:
- bundle install

branches:
  only:
    - master
    - /^(\d+\.)?(\d+\.)?\d+(-\w+)?$/

script:
- ./travis-build.sh
