language: objective-c
xcode_project: JenkinsiOS.xcodeproj
osx_image: xcode9.1
xcode_sdk: iphonesimulator11.1

cache:
- bundler

before_install:
- bundle install

branches:
  only:
    - master
    - /^(\d+\.)?(\d+\.)?\d+(-\w+)?$/

script:
- ./travis-build.sh
