language: objective-c
xcode_project: JenkinsiOS.xcodeproj
osx_image: xcode10
xcode_sdk: iphonesimulator12.0

cache:
  directories:
  - "${HOME}/google-cloud-sdk"
  - bundler

before_install:
- bundle install

branches:
  only:
    - master
    - /^(\d+\.)?(\d+\.)?\d+(-\w+)?$/

script:
- ./travis-build.sh
