language: objective-c
xcode_project: JenkinsiOS.xcodeproj
xcode_scheme: JenkinsiOSTests
osx_image: xcode8.2
xcode_sdk: iphonesimulator10.0

branches:
  only:
    - master
    - /^(\d+\.)?(\d+\.)?\d+(-\w+)?$/

script:
- ./travis-build.sh
